const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

test('sync_stats reads ownerOpenId and legacy _openid scoped player data', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'cloudfunctions', 'poker_data', 'index.js'), 'utf8')
  const syncStats = source.match(/async function syncStats\(event, ownerOpenId\) \{[\s\S]*?\r?\n\}\r?\n\r?\nasync function exportAgentData/)
  const stableHands = source.match(/async function fetchStableOwnedHandData\(playerId, ownerOpenId\) \{[\s\S]*?\r?\n\}\r?\n\r?\nfunction handExportEvidence/)

  assert.ok(syncStats, 'syncStats implementation must remain source-auditable')
  assert.ok(stableHands, 'stable hand loader implementation must remain source-auditable')
  assert.match(syncStats[0], /let sessions = \(await fetchOwnedByPlayer\(COLLECTIONS\.sessions, playerId, ownerOpenId\)\)\.map\(cleanCloudDoc\)/)
  assert.match(syncStats[0], /let hands = await loadStatsHands\(playerId\)/)
  assert.match(syncStats[0], /const stable = await fetchStableOwnedHandData\(targetPlayerId, ownerOpenId\)/)
  assert.doesNotMatch(syncStats[0], /fetchAll\(/)
  assert.match(stableHands[0], /const before = await fetchOwnedByPlayer\(COLLECTIONS\.hands, playerId, ownerOpenId\)/)
  assert.match(stableHands[0], /fetchOwnedByPlayer\(COLLECTIONS\.handActions, playerId, ownerOpenId\)/)
  assert.match(stableHands[0], /const after = await fetchOwnedByPlayer\(COLLECTIONS\.hands, playerId, ownerOpenId\)/)
  assert.doesNotMatch(stableHands[0], /fetchAll\(/)
})
