const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const source = fs.readFileSync(path.join(__dirname, '..', 'pages', 'player-note-detail', 'player-note-detail.js'), 'utf8')
const wxml = fs.readFileSync(path.join(__dirname, '..', 'pages', 'player-note-detail', 'player-note-detail.wxml'), 'utf8')

assert.match(source, /function cropPlayerAvatar/, 'player photo selection should enter an avatar crop step')
assert.match(source, /wx\.cropImage/, 'avatar crop should use native wx.cropImage when available')
assert.match(source, /cropScale:\s*'1:1'/, 'avatar crop should force a square crop for circular avatars')
assert.match(source, /const croppedPath = await cropPlayerAvatar\(tempFilePath\)/, 'chosen photo should be cropped before local save and upload')
assert.match(source, /AVATAR_UPLOAD_MAX_BYTES\s*=\s*2\s*\*\s*1024\s*\*\s*1024/, 'avatar cloud upload should enforce the 2MB WeChat upload limit')
assert.match(source, /function getLocalFileSize/, 'avatar upload should inspect local file size before cloud upload')
assert.match(source, /wx\.getFileInfo/, 'avatar upload should use wx.getFileInfo for source size checks')
assert.match(source, /function compressPlayerAvatar/, 'avatar upload should compress cropped images before saving and uploading')
assert.match(source, /wx\.compressImage/, 'avatar upload should use wx.compressImage when available')
assert.match(source, /const uploadPath = await preparePlayerAvatarForUpload\(croppedPath\)/, 'cropped avatars should be compressed before cloud upload')
assert.match(source, /const avatar = await uploadPlayerPhoto\(uploadPath\)/, 'avatar upload should use the compressed temporary file')
assert.match(source, /if \(avatar\.avatarFileId\)/, 'avatar form state should only use a successful cloud file id')
assert.match(source, /avatarCache\.cacheLocalAvatar\(avatar\.avatarFileId,\s*uploadPath\)/, 'uploaded avatars should be cached locally for fast display')
assert.match(source, /avatarUrl: fileId,\s*avatarFileId: fileId/s, 'avatarUrl and avatarFileId should both come from cloud storage fileID')
assert.doesNotMatch(source, /avatar\.avatarUrl \|\| savedPath/, 'local saved paths should not be stored as formal avatarUrl')
assert.match(source, /uploadSize > AVATAR_UPLOAD_MAX_BYTES/, 'oversized avatars should not call cloud uploadFile')
assert.match(wxml, /头像预览|裁剪|缩放/, 'photo editor should tell users the avatar can be cropped or scaled')

console.log('player notes avatar crop tests passed')
