const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const launchAnimation = require(path.join(root, 'utils', 'launch-animation'))

launchAnimation.__test.reset()
assert.strictEqual(launchAnimation.getLaunchAnimationDuration(), 2950)
assert.strictEqual(launchAnimation.consumeLaunchAnimation(), true)
assert.strictEqual(launchAnimation.consumeLaunchAnimation(), false)

const js = fs.readFileSync(path.join(root, 'pages', 'session-list', 'session-list.js'), 'utf8')
const wxml = fs.readFileSync(path.join(root, 'pages', 'session-list', 'session-list.wxml'), 'utf8')
const wxss = fs.readFileSync(path.join(root, 'pages', 'session-list', 'session-list.wxss'), 'utf8')

assert.match(js, /showLaunchAnimation:\s*true/)
assert.match(js, /consumeLaunchAnimation\(\)/)
assert.match(js, /getLaunchAnimationDuration\(\)/)
assert.match(js, /scheduleStatsPrefetch\(dataService\)/)
assert.match(js, /clearTimeout\(this\.launchStatsPrefetchTimer\)/)
assert.match(js, /clearTimeout\(this\.launchAnimationTimer\)/)
assert.match(wxml, /wx:if="\{\{showLaunchAnimation\}\}"/)
assert.match(wxml, /launch-phantom-five-cards-v1\.jpg/)
assert.match(wxml, />智牌屋</)
assert.match(wxml, />AI-POWERED POKER INSIGHT</)
assert.doesNotMatch(wxml, /READ THE TABLE/)
assert.match(wxss, /@keyframes sessionLaunchHeroFloat/)
assert.match(wxss, /animation:\s*sessionLaunchExit 240ms[^;]+2710ms/)
assert.match(wxss, /animation:\s*sessionLaunchCutAcross 520ms[^;]+2430ms/)
assert.doesNotMatch(wxml, /session-launch-dots/)
assert.doesNotMatch(wxss, /\.session-launch-dots/)
assert.match(wxss, /translate3d\(2\.5%, -5rpx, 0\)/)
