const assert = require('assert')
const fs = require('fs')

const js = fs.readFileSync('pages/session-list/session-list.js', 'utf8')
const wxml = fs.readFileSync('pages/session-list/session-list.wxml', 'utf8')
const wxss = fs.readFileSync('pages/session-list/session-list.wxss', 'utf8')

assert.match(wxml, /session-swipe-row/)
assert.match(wxml, /catchtap="editSessionFromList"/)
assert.match(wxml, /catchtap="deleteSessionFromList"/)
assert.match(wxml, /bindtouchstart="onSessionItemTouchStart"/)
assert.match(wxml, /bindtouchmove="onSessionItemTouchMove"/)
assert.match(wxml, /bindtouchend="onSessionItemTouchEnd"/)
assert.match(js, /swipedSessionId/)
assert.match(js, /if \(this\.data\.touchMoved\)/)
assert.match(js, /if \(!res\.confirm\) return/)
assert.match(js, /dataService\.deleteSession\(sessionId\)/)
assert.match(js, /该 Session、该场全部手牌、行动记录及结算记录都会永久删除且无法恢复/)
assert.match(js, /删除失败/)
assert.match(wxss, /\.session-swipe-row\.open \.session-swipe-content[\s\S]*translateX\(-176rpx\)/)
assert.match(wxss, /\.session-swipe-action\.edit[\s\S]*#0aa8d6/)
assert.match(wxss, /\.session-swipe-action\.delete[\s\S]*#ef233c/)

console.log('session swipe action tests passed')
