const assert = require('node:assert/strict')
const fs = require('node:fs')

const wxml = fs.readFileSync('pages/session-list/session-list.wxml', 'utf8')
const wxss = fs.readFileSync('pages/session-list/session-list.wxss', 'utf8')

assert.match(wxml, /class="card session-history-head-card"/)
assert.match(wxml, /class="session-history-title"[\s\S]*全部[\s\S]*Session/)
assert.match(wxml, /class="primary-btn small-btn new-session-btn session-history-create[^"]*"[\s\S]*\+ 新建/)
assert.doesNotMatch(wxml, /session-history-updated|historyUpdatedDate/)
assert.match(wxml, /<view class="primary-btn small-btn new-session-btn session-history-create[^"]*" role="button" bindtap="goNewSession">[^<]+<\/view>/)
assert.doesNotMatch(wxml, /<button class="[^"]*session-history-create/)
assert.match(wxml, /class="session-swipe-content session-history-card \{\{item\.totalProfitTone\}\}"/)
assert.match(wxml, /class="session-history-result \{\{item\.totalProfitTone\}\}"/)
assert.match(wxml, /class="session-history-result-label">本场输赢/)
assert.match(wxml, /class="session-history-result-value \{\{item\.totalProfitDisplay\.length > 10 \? 'compact' : ''\}\}">\{\{item\.totalProfitDisplay\}\}/)
assert.match(wxml, /买入 \{\{item\.buyIn\}\}/)
assert.match(wxml, /手牌 \{\{item\.handCount\}\}/)
assert.match(wxml, /session-history-metric-icon[\s\S]*p5-buyin-v251\.png/)
assert.match(wxml, /session-history-metric-icon[\s\S]*p5-full-v251\.png/)
assert.match(wxml, /class="session-history-summary-icon"[\s\S]*p5-quick-v251\.png/)
assert.match(wxml, /catchtap="openSessionSummary"/)
assert.match(wxml, /bindtap="goSessionDetail"/)
assert.match(wxml, /bindtouchstart="onSessionItemTouchStart"/)
assert.doesNotMatch(wxml, /session-history-(?:index|number|sequence)/)

assert.match(wxss, /\.session-history-title\s*\{[\s\S]*?clip-path:\s*polygon/)
assert.match(wxss, /\.session-history-title text:last-child\s*\{[\s\S]*?font-style:\s*italic/)
assert.match(wxss, /\.session-history-create\s*\{[\s\S]*?clip-path:\s*polygon/)
assert.match(wxss, /\.session-history-create\s*\{[\s\S]*?box-sizing:\s*border-box[\s\S]*?max-width:\s*100%/)
assert.match(wxss, /\.session-history-create\s*\{[\s\S]*?display:\s*flex[\s\S]*?align-items:\s*center[\s\S]*?justify-content:\s*center/)
assert.match(wxss, /\.session-history-head-card\s*\{[\s\S]*?overflow:\s*hidden/)
assert.match(wxss, /\.session-history-head-card\s*\{[\s\S]*?margin-left:\s*-12rpx[\s\S]*?margin-right:\s*-12rpx/)
assert.match(wxss, /\.session-history-head-card::after\s*\{[\s\S]*?height:\s*2rpx[\s\S]*?background:\s*#e60012/)
assert.match(wxss, /\.session-history-head\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) 244rpx[\s\S]*?gap:\s*64rpx/)
assert.match(wxss, /\.session-history-title\s*\{[\s\S]*?padding:\s*26rpx 44rpx 26rpx 32rpx[\s\S]*?font-size:\s*52rpx[\s\S]*?font-style:\s*italic/)
assert.match(wxss, /\.session-history-create\s*\{[\s\S]*?height:\s*92rpx/)
assert.match(wxss, /\.session-history-list-card\s*\{[\s\S]*?margin-left:\s*-12rpx[\s\S]*?margin-right:\s*-12rpx/)
assert.match(wxss, /\.session-history-card-layout\s*\{[\s\S]*?grid-template-columns:/)
assert.match(wxss, /\.session-history-card-layout\s*\{[\s\S]*?grid-template-rows:\s*118rpx 72rpx/)
assert.match(wxss, /\.session-history-info\s*\{[\s\S]*?padding:\s*24rpx 14rpx 8rpx 60rpx/)
assert.doesNotMatch(wxss, /\.session-history-result\s*\{[^}]*clip-path:/)
assert.match(wxss, /\.session-history-result\s*\{[^}]*overflow:\s*visible/)
assert.match(wxss, /\.session-history-result::before\s*\{[\s\S]*?clip-path:\s*polygon\(52% 0/)
assert.match(wxss, /\.session-history-result\.positive::before\s*\{[\s\S]*?rgba\(0, 209, 255, 0\.24\)/)
assert.match(wxss, /\.session-history-result\.negative::before\s*\{[\s\S]*?rgba\(230, 0, 18, 0\.30\)/)
assert.doesNotMatch(wxss, /\.session-history-result\s*\{[\s\S]*?filter:\s*drop-shadow/)
assert.match(wxss, /\.session-history-result-value\s*\{[\s\S]*?white-space:\s*nowrap/)
assert.match(wxss, /\.session-history-result-value\s*\{[\s\S]*?text-shadow:\s*none/)
assert.match(wxss, /\.session-history-result-value\s*\{[\s\S]*?font-size:\s*48rpx/)
assert.match(wxss, /\.session-history-result-value\.compact\s*\{[\s\S]*?font-size:/)
assert.match(wxss, /\.session-history-result\.positive\s*\{[\s\S]*?#00d1ff/)
assert.match(wxss, /\.session-history-result\.negative\s*\{[\s\S]*?#ff3b3b/)
assert.match(wxss, /\.session-history-card-layout::before\s*\{[\s\S]*?pointer-events:\s*none/)
assert.match(wxss, /\.session-history-footer\s*\{[\s\S]*?grid-template-columns:\s*310rpx 120rpx 108rpx[\s\S]*?justify-content:\s*start/)
assert.doesNotMatch(
  wxss,
  /@media\s*\(max-width:\s*360px\)/,
  'Session 历史列表不应在窄屏上二次缩小，否则真机与模拟器的字号和底栏间距会不一致'
)
assert.match(wxss, /\.session-history-metric-icon\s*\{[\s\S]*?filter:\s*grayscale\(1\)/)
assert.match(wxss, /\.session-history-metrics\s*\{[\s\S]*?font-size:\s*22rpx/)
assert.match(wxss, /\.session-history-metric-icon\s*\{[\s\S]*?width:\s*28rpx[\s\S]*?transform:\s*scale\(1\.65\)/)
assert.match(wxss, /\.session-summary-trigger\.session-history-summary\s*\{[\s\S]*?border-radius:\s*8rpx[\s\S]*?clip-path:\s*polygon/)
assert.match(wxss, /\.session-history-summary-icon\s*\{[\s\S]*?width:\s*22rpx/)

console.log('session list P5 history redesign ok')
