const assert = require('node:assert/strict')
const fs = require('node:fs')

const wxml = fs.readFileSync('pages/session-list/session-list.wxml', 'utf8')
const wxss = fs.readFileSync('pages/session-list/session-list.wxss', 'utf8')

assert.match(wxml, /class="card session-history-head-card"/)
assert.match(wxml, /class="session-history-title"[\s\S]*全部[\s\S]*Session/)
assert.match(wxml, /class="primary-btn small-btn new-session-btn session-history-create[^"]*"[\s\S]*\+ 新建/)
assert.match(wxml, /class="session-swipe-content session-history-card \{\{item\.totalProfitTone\}\}"/)
assert.match(wxml, /class="session-history-result \{\{item\.totalProfitTone\}\}"/)
assert.match(wxml, /class="session-history-result-label">本场输赢/)
assert.match(wxml, /class="session-history-result-value \{\{item\.totalProfitDisplay\.length > 10 \? 'compact' : ''\}\}">\{\{item\.totalProfitDisplay\}\}/)
assert.match(wxml, /买入 \{\{item\.buyIn\}\}/)
assert.match(wxml, /手牌 \{\{item\.handCount\}\}/)
assert.match(wxml, /catchtap="openSessionSummary"/)
assert.match(wxml, /bindtap="goSessionDetail"/)
assert.match(wxml, /bindtouchstart="onSessionItemTouchStart"/)
assert.doesNotMatch(wxml, /session-history-(?:index|number|sequence)/)

assert.match(wxss, /\.session-history-title\s*\{[\s\S]*?clip-path:\s*polygon/)
assert.match(wxss, /\.session-history-create\s*\{[\s\S]*?clip-path:\s*polygon/)
assert.match(wxss, /\.session-history-card-layout\s*\{[\s\S]*?grid-template-columns:/)
assert.match(wxss, /\.session-history-result\s*\{[\s\S]*?clip-path:\s*polygon/)
assert.match(wxss, /\.session-history-result-value\s*\{[\s\S]*?white-space:\s*nowrap/)
assert.match(wxss, /\.session-history-result-value\.compact\s*\{[\s\S]*?font-size:/)
assert.match(wxss, /\.session-history-result\.positive\s*\{[\s\S]*?#00d1ff/)
assert.match(wxss, /\.session-history-result\.negative\s*\{[\s\S]*?#ff3b3b/)
assert.match(wxss, /\.session-history-card-layout::before\s*\{[\s\S]*?pointer-events:\s*none/)

console.log('session list P5 history redesign ok')
