const assert = require('assert')
const fs = require('fs')

const js = fs.readFileSync('pages/session-detail/session-detail.js', 'utf8')
const wxml = fs.readFileSync('pages/session-detail/session-detail.wxml', 'utf8')
const wxss = fs.readFileSync('pages/session-detail/session-detail.wxss', 'utf8')

assert.match(js, /require\('\.\.\/\.\.\/utils\/session-duration'\)/)
assert.match(js, /refreshDurationDisplay\(\)/)
assert.match(js, /startDurationClock\(\)/)
assert.match(js, /stopDurationClock\(\)/)
assert.match(js, /onHide\(\)\s*\{\s*this\.stopDurationClock\(\)/)
assert.match(js, /onUnload\(\)\s*\{\s*this\.stopDurationClock\(\)/)
assert.match(js, /60000\s*-\s*\(Date\.now\(\)\s*%\s*60000\)/)
assert.match(wxml, /class="session-duration-instrument"/)
assert.match(wxml, /\{\{durationLabel\}\}/)
assert.match(wxml, /\{\{durationDisplay\}\}/)
assert.match(wxml, /SESSION 总时长/)
assert.match(wxss, /\.session-duration-value[\s\S]*font-variant-numeric:\s*tabular-nums/)
assert.match(wxss, /\.session-duration-rule[\s\S]*linear-gradient/)

console.log('session detail duration ui tests passed')
