const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const wxml = fs.readFileSync(path.join(root, 'pages/stats/stats.wxml'), 'utf8')
const wxss = fs.readFileSync(path.join(root, 'pages/stats/stats.wxss'), 'utf8')

assert.ok(wxml.includes('stats-hero'), 'stats page should render the prototype hero report')
assert.ok(wxml.includes('<view class="stats-title">统计</view>'), 'stats hero title should be concise')
assert.equal(wxml.includes('统计指挥室'), false, 'stats hero should not use the longer title copy')
assert.ok(wxml.includes('stats-range-segment'), 'stats page should expose the range segmented control')
assert.ok(wxml.includes('经营表现'), 'stats page should include the performance board section')
assert.ok(wxml.includes('战术诊断'), 'stats page should include the tactical diagnosis section')
assert.ok(wxml.includes('波动与大底池'), 'stats page should include the volatility section')
assert.ok(wxml.includes('复盘优先级'), 'stats page should include the review priority section')
assert.equal(wxml.includes('stats-section-mark'), false, 'stats sections should not render numeric section marks')
assert.equal(/\ufffd\/(?:view|button|text|scroll-view|picker|textarea|input)>/.test(wxml), false)
assert.equal(/\?\/(?:view|button|text|scroll-view|picker|textarea|input)>/.test(wxml), false)

assert.ok(wxss.includes('.stats-hero'), 'stats page should include hero-specific styling')
assert.ok(wxss.includes('.stats-slash'), 'stats page should include P5-like slash accents')
assert.equal(wxml.includes('stats-slash-b'), false, 'stats hero should not render the lower slash over KPI cards')
assert.ok(wxss.includes('z-index: 0;'), 'slash accents should stay below metric content')
assert.ok(wxss.includes('.stats-bar-fill'), 'stats page should include CSS bar styling')

console.log('stats prototype smoke test passed')
