const CLOUD_ENV_ID = 'cloud1-d3ggy9aq3be912e34'
const PREFER_CLOUD = true
const AUTO_CLOUD_BOOTSTRAP = true
const AI_REMINDER_SUBSCRIBE_TEMPLATE_ID = 'cMnLCh7VSbPFR8PzOg0FOteglq-3AaRGsblNAzdShos'

module.exports = {
  CLOUD_ENV_ID,
  PREFER_CLOUD,
  AUTO_CLOUD_BOOTSTRAP,
  AI_REMINDER_SUBSCRIBE_TEMPLATE_ID
}
